# Generated by Django 2.2.7 on 2020-03-15 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzer', '0001_initial'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date(2020, 5, 14))),
                ('units', models.IntegerField(default=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analyzer.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='signup.CustomUser')),
            ],
        ),
    ]
