# Generated by Django 2.2.7 on 2020-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='file',
            field=models.FilePathField(blank=True, editable=False),
        ),
    ]
