# Generated by Django 2.2.7 on 2020-04-27 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_investment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 6, 26)),
        ),
    ]
