# Generated by Django 3.0.5 on 2020-05-09 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200427_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
    ]
